language: elixir
sudo: required
services:
  - docker
before_install:
  - docker pull laslabs/alpine-cfssl
  - docker run -d -p 127.0.0.1:8888:8080 laslabs/alpine-cfssl
  - docker ps -a
matrix:
  include:
    - elixir: 1.7
      otp_release: 20.0
    - elixir: 1.8
      otp_release: 21.0
    - elixir: 1.9
      otp_release: 21.0
    - elixir: 1.10
      otp_release: 22.0
after_script:
  - mix coveralls.travis
